### ISSUE TITLE
Xogar 2.0.0 does nothing

### ISSUE THREAD

**Issue by Balkhog** [indyK1ng/Xogar#35]
Hi guys !
Don't know if you're still working on this project but know that I'm using it frequently.
I was using 1.3.4 for a bit and didn't notice there was a 2.0.0 until now.
Like I said, 2.0.0 is simply not working for me while 1.3.4 works perfectly. I don't know anything about code but if there's anything I can provide to help let me know.
I think I've managed to launch 2.0.0 a few times and there was a message saying that Xogar couldn't find the steam directory and I  think you got this issue before.
So yeah, don't know if you're still working in the project, if not I'll continue using 1.3.4 even if I would love to see the new UI.
Thanks for your work.

**Comment by BlueRaja** [comment]
Fixed in [v2.0.1](https://github.com/indyK1ng/Xogar/releases/latest).

Please verify and reopen if issue is still occurring
